### ISSUE TITLE
End-to-end Hub setup guide (getting started)

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/project-management-pipeline#123]
Do last

**Comment by ArjunBhuptani** [comment]
We'll need to review this and add to it once we have everything done on the Hub. Putting it into this sprint for now.

**Comment by hthillman** [comment]
@ArjunBhuptani 

1, 3, 4, 5 are all covered here https://docs.connext.network/~/drafts/-LMhftcfTvKwQu8-JODn/primary/
