### ISSUE TITLE
Fix About and Jobs pages on website

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/project-management-pipeline#144]
Mockups are done in webflow. Need to be cleaned up for desktop/mobile and then deployed

- [x] cleaned up
- [ ] deployed

**Comment by ArjunBhuptani** [comment]
Probably some design stuff in here too which will make this tougher

**Comment by hthillman** [comment]
todo

- [ ]  Spacing for positioning statement, make it the same width as the laptop (40% width on the container should do it)
- [ ] for team section, use the standard font for the title (same as other sections) and the same spacing
- [ ]  Move team to another page? Ive never liked the trend of haivng your team on the front page, it's too much like a pitch deck
- [ ]  "Connext is unlocking the peer-to-peer economy of the future. If you want to help, reach out to support@connext.network " should be in different, smaller font. Try to match the other text on the page.

**Comment by hthillman** [comment]
@ArjunBhuptani what's the status here? obviously on the back burner right now but where does the version that you cleaned up stand?
