### ISSUE TITLE
Client updates

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/project-management-pipeline#150]
Brain dump -- fixes for happy case tests. can split into separate issues

- [x] getchannelbypartyA 
    - [x] hub needs to autojoin, poll database and call contract functions
- [x] getThreadbypartyA
- [x] createChannelUpdateOnThreadOpen
    - may have to make changes based on parameters but also may just work
- [x] post to hub to create virtual channel (will probably be fine but might be small changes)
- [x] payments objects have metas, may or may not need these
- [x] new updateThread function 
- [x] new updateChannel function
- [ ] getLatestChannelState -  allow hub to sort by most recent signer

EDIT:: OUTDATED, see below

**Comment by ArjunBhuptani** [comment]
Fixed stubhub tests, running through tests to fix client
